'use strict'

var gulp = require('gulp');
var gulpLoadPlugins = require('gulp-load-plugins');
var browserSync = require('browser-sync');
var plugins = gulpLoadPlugins();

gulp.task('svg:inline', function() {
  return gulp.src('./src/svg/inline/*.svg').pipe(plugins.plumber({
    errorHandler: onError
  })).pipe(plugins.svgmin()).pipe(plugins.svgstore({
    fileName: 'symbols.svg',
    inlineSvg: true
  })).pipe(plugins.cheerio({
    run: function(jQuery) {
      jQuery('[fill]').removeAttr('fill');
      return jQuery('[stroke]').removeAttr('stroke');
    },
    parserOptions: {
      xmlMode: true
    }
  })).pipe(gulp.dest('./src/jade/layouts/includes'));
});

gulp.task('svg:external', function() {
  return gulp.src('./src/svg/external/*.svg').pipe(plugins.plumber({
    errorHandler: onError
  })).pipe(plugins.svgmin()).pipe(plugins.svgstore({
    fileName: 'symbols.svg'
  })).pipe(plugins.cheerio({
    run: function(jQuery) {
      jQuery('[fill]').removeAttr('fill');
      return jQuery('[stroke]').removeAttr('stroke');
    },
    parserOptions: {
      xmlMode: true
    }
  })).pipe(gulp.dest(config.exportPath + '/svg/'));
});

// ---
// generated by coffee-script 1.9.2
